# Generated by Django 4.2.2 on 2023-10-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_advertisements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="advertisement",
            table="advertisements",
        ),
    ]
