# Generated by Django 4.2.2 on 2023-10-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_advertisements", "0003_advertisement_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="image",
            field=models.ImageField(
                default="", upload_to="advertisements2/", verbose_name="Изображение"
            ),
            preserve_default=False,
        ),
    ]
